### ISSUE TITLE
Add support simuvex installation on macOS 10.11.6.

### ISSUE THREAD

**Issue by feicong** [angr/simuvex#88] opened 2017-02-12 01:26 UTC
compile libVEX with clang got this error!
```
$ python setup.py install
make -f Makefile-gcc
cc -c -Wall -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wmissing-declarations -Wwrite-strings -Wformat -Wformat-security -std=gnu99 -fpic -w  -g -O2 -fstrict-aliasing -malign-double -Ipub -Ipriv -o priv/ir_defs.o priv/ir_defs.c
clang: error: unknown argument: '-malign-double'
make[1]: *** [priv/ir_defs.o] Error 1
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    'simuvex': ['lib/*']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Library/Python/2.7/site-packages/setuptools/dist.py", line 317, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/Library/Python/2.7/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
    replace_conflicting=True,
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/Library/Python/2.7/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 1108, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: Unable to build libVEX.
```

then use gcc6.
```
$ CC=/usr/local/bin/gcc-6 python setup.py install
make -f Makefile-gcc
/usr/local/bin/gcc-6 -c -Wall -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wmissing-declarations -Wwrite-strings -Wformat -Wformat-security -std=gnu99 -fpic -w  -g -O2 -fstrict-aliasing -malign-double -Ipub -Ipriv -o priv/ir_defs.o priv/ir_defs.c
/usr/local/bin/gcc-6 -c -Wall -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wmissing-declarations -Wwrite-strings -Wformat -Wformat-security -std=gnu99 -fpic -w  -g -O2 -fstrict-aliasing -malign-double -Ipub -Ipriv -o priv/ir_match.o priv/ir_match.c
......
gcc -c -O2 -shared -fPIC --std=c99 -I ../vex-master/pub pyvex.c
gcc -c -O2 -shared -fPIC --std=c99 -I ../vex-master/pub logging.c
clang: clangwarning: : argument unused during compilation: '-shared'warning
: argument unused during compilation: '-shared'
pyvex.c:142:14: warning: incompatible pointer types passing 'void (*)(void)' to
      parameter of type 'void (*)(void) __attribute__((noreturn))'
      [-Wincompatible-pointer-types]
        LibVEX_Init(&failure_exit,
                    ^~~~~~~~~~~~~
../vex-master/pub/libvex.h:565:11: note: passing argument to parameter
      'failure_exit' here
   void (*failure_exit) ( void ),
          ^
pyvex.c:435:2: warning: add explicit braces to avoid dangling else
      [-Wdangling-else]
        catch (VEXError)
        ^
../vex-master/pub/e4c_lite.h:27:22: note: expanded from macro 'catch'
# define catch(type) E4C_CATCH(type)
                     ^
../vex-master/pub/e4c_lite.h:63:25: note: expanded from macro 'E4C_CATCH'
#define E4C_CATCH(type) else if(e4c.frame[e4c.frames].stage == e4c_catch...
                        ^
pyvex.c:465:2: warning: add explicit braces to avoid dangling else
      [-Wdangling-else]
        catch (VEXError)
        ^
../vex-master/pub/e4c_lite.h:27:22: note: expanded from macro 'catch'
# define catch(type) E4C_CATCH(type)
                     ^
../vex-master/pub/e4c_lite.h:63:25: note: expanded from macro 'E4C_CATCH'
#define E4C_CATCH(type) else if(e4c.frame[e4c.frames].stage == e4c_catch...
                        ^
3 warnings generated.
gcc -O2 -shared -fPIC --std=c99 -I ../vex-master/pub -o libpyvex.dylib pyvex.o logging.o ../vex-master/libvex.a -Wl,-install_name,libpyvex.dylib
ar rcs libpyvex.a pyvex.o logging.o
No handlers could be found for logger "cffier"
Exception("Couldn't process pyvex headers - set CPP env var",)
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    'simuvex': ['lib/*']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Library/Python/2.7/site-packages/setuptools/dist.py", line 317, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/Library/Python/2.7/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
    replace_conflicting=True,
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/Library/Python/2.7/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    run_setup(setup_script, args)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/folders/rd/mts0362j0n92rq0z1cnmdb580000gn/T/easy_install-GXsdJs/pyvex-6.7.1.31/setup.py", line 143, in <module>

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/folders/rd/mts0362j0n92rq0z1cnmdb580000gn/T/easy_install-GXsdJs/pyvex-6.7.1.31/setup.py", line 118, in run
    }
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/folders/rd/mts0362j0n92rq0z1cnmdb580000gn/T/easy_install-GXsdJs/pyvex-6.7.1.31/setup.py", line 100, in run
    packages=packages,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 349, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/util.py", line 309, in execute
    func(*args)
  File "/var/folders/rd/mts0362j0n92rq0z1cnmdb580000gn/T/easy_install-GXsdJs/pyvex-6.7.1.31/setup.py", line 90, in _build_ffi
    sys.argv.append('manylinux1_' + platform.machine())
  File "/var/folders/rd/mts0362j0n92rq0z1cnmdb580000gn/T/easy_install-GXsdJs/pyvex-6.7.1.31/make_ffi.py", line 83, in doit
Exception: Couldn't process pyvex headers - set CPP env var
```

plz let me know,how to resolve it?

**Comment by rhelmot** [comment] 2017-02-12 01:37
Duplicate of https://github.com/angr/pyvex/issues/56

Patch to fix is here: https://github.com/angr/pyvex/pull/58

**Closed by rhelmot** 2017-02-12 01:37 UTC
